repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.0
    hooks:
    -   id: ruff # linter + import sorting
        args: [--fix]
    -   id: ruff-format # formatter (replaces black)
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-merge-conflict # prevent committing files with merge conflicts
-   repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    -   id: codespell # Spellchecker
-   repo: local
    hooks:
    -   id: flynt
        name: flynt
        entry: flynt
        args: [--fail-on-change]
        types: [python]
        language: python
        additional_dependencies:
            - flynt
