[build-system]
requires = ["oldest-supported-numpy", "cython", "setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
skip = ["cp36-*", "cp37-*", "pp37-*"]
test-command = "pytest {package}/test"
test-requires = ["pytest", "scipy"]
