name: Python Unit Testing using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        conda config --add channels conda-forge
    - name: Install dependencies
      run: |
        conda install flake8 pytest-cov
        conda install pre-commit codespell
        pre-commit install
    - name: Install package
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        pytest --cov cached_interpolate -ra --color yes --cov-report=xml --junitxml=pytest.xml
    - name: Publish coverage to Codecov
      uses: codecov/codecov-action@v1.2.1
      with:
        files: coverage.xml
        flags: python${{ matrix.python-version }}
    - name: Coverage report
      run: python -m coverage report --show-missing
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: pytest-${{ matrix.python-version }}
        path: pytest.xml
